// Generated by gencpp from file marker_visualizer/marker_info.msg
// DO NOT EDIT!


#ifndef MARKER_VISUALIZER_MESSAGE_MARKER_INFO_H
#define MARKER_VISUALIZER_MESSAGE_MARKER_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marker_visualizer
{
template <class ContainerAllocator>
struct marker_info_
{
  typedef marker_info_<ContainerAllocator> Type;

  marker_info_()
    : shape()
    , x(0)
    , y(0)  {
    }
  marker_info_(const ContainerAllocator& _alloc)
    : shape(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shape_type;
  _shape_type shape;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::marker_visualizer::marker_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_visualizer::marker_info_<ContainerAllocator> const> ConstPtr;

}; // struct marker_info_

typedef ::marker_visualizer::marker_info_<std::allocator<void> > marker_info;

typedef boost::shared_ptr< ::marker_visualizer::marker_info > marker_infoPtr;
typedef boost::shared_ptr< ::marker_visualizer::marker_info const> marker_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_visualizer::marker_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_visualizer::marker_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marker_visualizer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'marker_visualizer': ['/home/jdrjk0000/catkin_ws/src/marker_visualizer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marker_visualizer::marker_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_visualizer::marker_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_visualizer::marker_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_visualizer::marker_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_visualizer::marker_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_visualizer::marker_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_visualizer::marker_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ecc62f7666cd773c0264730a6c13291";
  }

  static const char* value(const ::marker_visualizer::marker_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ecc62f7666cd773ULL;
  static const uint64_t static_value2 = 0xc0264730a6c13291ULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_visualizer::marker_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_visualizer/marker_info";
  }

  static const char* value(const ::marker_visualizer::marker_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_visualizer::marker_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string shape\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::marker_visualizer::marker_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_visualizer::marker_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shape);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct marker_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_visualizer::marker_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_visualizer::marker_info_<ContainerAllocator>& v)
  {
    s << indent << "shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shape);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_VISUALIZER_MESSAGE_MARKER_INFO_H
