// Generated by gencpp from file service_tutorials/SrvTutorial.msg
// DO NOT EDIT!


#ifndef SERVICE_TUTORIALS_MESSAGE_SRVTUTORIAL_H
#define SERVICE_TUTORIALS_MESSAGE_SRVTUTORIAL_H

#include <ros/service_traits.h>


#include <service_tutorials/SrvTutorialRequest.h>
#include <service_tutorials/SrvTutorialResponse.h>


namespace service_tutorials
{

struct SrvTutorial
{

typedef SrvTutorialRequest Request;
typedef SrvTutorialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvTutorial
} // namespace service_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_tutorials::SrvTutorial > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::service_tutorials::SrvTutorial&) { return value(); }
};

template<>
struct DataType< ::service_tutorials::SrvTutorial > {
  static const char* value()
  {
    return "service_tutorials/SrvTutorial";
  }

  static const char* value(const ::service_tutorials::SrvTutorial&) { return value(); }
};


// service_traits::MD5Sum< ::service_tutorials::SrvTutorialRequest> should match 
// service_traits::MD5Sum< ::service_tutorials::SrvTutorial > 
template<>
struct MD5Sum< ::service_tutorials::SrvTutorialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_tutorials::SrvTutorial >::value();
  }
  static const char* value(const ::service_tutorials::SrvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_tutorials::SrvTutorialRequest> should match 
// service_traits::DataType< ::service_tutorials::SrvTutorial > 
template<>
struct DataType< ::service_tutorials::SrvTutorialRequest>
{
  static const char* value()
  {
    return DataType< ::service_tutorials::SrvTutorial >::value();
  }
  static const char* value(const ::service_tutorials::SrvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_tutorials::SrvTutorialResponse> should match 
// service_traits::MD5Sum< ::service_tutorials::SrvTutorial > 
template<>
struct MD5Sum< ::service_tutorials::SrvTutorialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_tutorials::SrvTutorial >::value();
  }
  static const char* value(const ::service_tutorials::SrvTutorialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_tutorials::SrvTutorialResponse> should match 
// service_traits::DataType< ::service_tutorials::SrvTutorial > 
template<>
struct DataType< ::service_tutorials::SrvTutorialResponse>
{
  static const char* value()
  {
    return DataType< ::service_tutorials::SrvTutorial >::value();
  }
  static const char* value(const ::service_tutorials::SrvTutorialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_TUTORIALS_MESSAGE_SRVTUTORIAL_H
