// Generated by gencpp from file multiple_topic_pkg/my_topic_two.msg
// DO NOT EDIT!


#ifndef MULTIPLE_TOPIC_PKG_MESSAGE_MY_TOPIC_TWO_H
#define MULTIPLE_TOPIC_PKG_MESSAGE_MY_TOPIC_TWO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiple_topic_pkg
{
template <class ContainerAllocator>
struct my_topic_two_
{
  typedef my_topic_two_<ContainerAllocator> Type;

  my_topic_two_()
    : data(0.0)  {
    }
  my_topic_two_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> const> ConstPtr;

}; // struct my_topic_two_

typedef ::multiple_topic_pkg::my_topic_two_<std::allocator<void> > my_topic_two;

typedef boost::shared_ptr< ::multiple_topic_pkg::my_topic_two > my_topic_twoPtr;
typedef boost::shared_ptr< ::multiple_topic_pkg::my_topic_two const> my_topic_twoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multiple_topic_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'multiple_topic_pkg': ['/home/jdrjk0000/catkin_ws/src/multiple_topic_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::multiple_topic_pkg::my_topic_two_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb28210bfa9d7c9ULL;
  static const uint64_t static_value2 = 0x1146260178d9a584ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiple_topic_pkg/my_topic_two";
  }

  static const char* value(const ::multiple_topic_pkg::my_topic_two_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data\n\
";
  }

  static const char* value(const ::multiple_topic_pkg::my_topic_two_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_topic_two_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiple_topic_pkg::my_topic_two_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiple_topic_pkg::my_topic_two_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLE_TOPIC_PKG_MESSAGE_MY_TOPIC_TWO_H
